### ISSUE TITLE
[URGENT] Blog is down

### ISSUE THREAD

**Issue by adelq** [pennlabs/blog#1]

**Comment by adamdom** [comment]
I'll take a look at this asap.

**Comment by adamdom** [comment]
We also have the option of just hosting on a third party and pointing our subdomain to it. That way we can test the validity of our blog without putting in too much effort. Tiff wanted to try focusing blog posts to getting user feedback. If we are pivoting in nature, it may not be a bad idea to switch platforms.

But I'll take a look and we can quickly fix it, then no problem.

**Comment by adelq** [comment]
Fixed (`service php7.0-fpm restart`). Not sure what's meant by the new focus, will talk to Tiffany about it.

**Comment by adelq** [comment]
Fixed by @ezwang
